---

- name: Checking key
  fail:
    msg: "Please provide a sealion_key!"
  when: sealion_key == ""

- name: Creating source folder
  file:
    path: /usr/local/src/sealion
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Checking sources
  stat:
    path: "/usr/local/src/sealion/sealion-agent-{{ sealion_version }}-noarch.tar.gz"
  register: sealion_source_file

- name: Downloading sources
  get_url:
    url: "https://s3.amazonaws.com/sealion.com/{{ sealion_version }}/sealion-agent-{{ sealion_version }}-noarch.tar.gz"
    dest: "/usr/local/src/sealion/sealion-agent-{{ sealion_version }}-noarch.tar.gz"
  when: not sealion_source_file.stat.exists

- name: Unpacking sources
  unarchive:
    src: "/usr/local/src/sealion/sealion-agent-{{ sealion_version }}-noarch.tar.gz"
    dest: /usr/local/src/sealion
    copy: no
  when: not sealion_source_file.stat.exists

- name: Installing sealion
  command: >
    ./install.sh --no-start -o {{ sealion_key }}
    chdir=/usr/local/src/sealion/sealion-agent
    creates=/etc/init.d/sealion
  when: not sealion_source_file.stat.exists

- name: Cleaning up
  file:
    path: /usr/local/src/sealion/sealion-agent
    state: absent
